### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by Elitedj** [MeiK2333/recent_contests#29]
获取数据时出现ERR_SSL_PROTOCOL_ERROR报错

**Comment by MeiK2333** [comment]
具体是哪个站点呢？

**Comment by Elitedj** [comment]
https://contests.sdutacm.cn/contests.json?include=Codeforces&include=LeetCode&include=AtCoder

**Comment by Elitedj** [comment]
> 具体是哪个站点呢？

https://contests.sdutacm.cn/contests.json?include=Codeforces&include=LeetCode&include=AtCoder

**Comment by MeiK2333** [comment]
哦哦，这个是搭建的服务器出问题了，现在已经好了

**Comment by Elitedj** [comment]
> 哦哦，这个是搭建的服务器出问题了，现在已经好了

ok了，👍🏻
